apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
data:
  postgres-db: cG9zdGdyZXM= # "postgres" in Base64
  postgres-user: cG9zdGdyZXM= # "postgres" in Base64
  postgres-password: cG9zdGdyZXNwdw== # "postgrespw" in Base64
