apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-frontend
spec:
  replicas: 2  # Anzahl der Instanzen
  selector:
    matchLabels:
      app: react-frontend
  template:
    metadata:
      labels:
        app: react-frontend
    spec:
      containers:
        - name: react-frontend
          image: frontend/react  # TODO Docker-Images erstellen...
          ports:
            - containerPort: 3000
