name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew clean bootJar

    - name: Build Docker Image
      run: docker build -t my-spring-app .

    - name: Docker Compose Up
      run: docker-compose up -d

    - name: Run Static Analysis
      run: ./gradlew sonarqube

    - name: Run Unit Tests
      run: ./gradlew test --tests backend/src/test/java/com/example/jwt
